### ISSUE TITLE
Wrong docker port in readme

### ISSUE THREAD

**Issue by dunderrrrrr** [Fairbanks-io/markdown-editor#66]
Hi! 

Seems like its the wrong docker container port in the readme. 

The port needs to be changed from 8888 to 8080 for the example to work. 

Chance:
```sudo docker run --name md-editor -d -p 8888:8888  jonfairbanks/markdown-editor```

To:
```sudo docker run --name md-editor -d -p 8888:8080 jonfairbanks/markdown-editor```

Maybe miner typo :)

**Comment by jonfairbanks** [comment]
Hi @dunderrrrrr, thanks for the report. Pushing an update to fix that.
